INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(-10, 'Room1', 1);
INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(-9, 'Room2', 1);

INSERT INTO LIGHT(ID, LEVEL,COLOR, STATUS, ROOM_ID) VALUES (-1, 8,250, 'ON', -10);
INSERT INTO LIGHT(ID, LEVEL,COLOR, STATUS, ROOM_ID) VALUES (-2, 11,302, 'OFF', -10);